osx_image: xcode9
language: objective-c

script:
- set -o pipefail && xcodebuild -workspace Project/FLTextFieldAutoCompleteExample.xcworkspace -scheme "FLTextFieldAutoCompleteExample" -sdk iphonesimulator -destination name="iPhone 8" clean build

notifications:
email: false
