osx_image: xcode9
language: objective-c

script:
- set -o pipefail && xcodebuild -project Project/FLTextFieldAutoCompleteExample.xcworkspace -scheme "FLTextFieldAutoCompleteExample" -sdk iphonesimulator -destination name="iPhone 8" clean build
- set -o pipefail && xcodebuild -project Project/FLTextFieldAutoCompleteExample.xcworkspace -scheme "FLTextFieldAutoCompleteExample" -sdk iphonesimulator -destination name="iPhone 8" -enableCodeCoverage YES test

notifications:
email: false
